CREATE TABLE Playlists (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  length integer NOT NULL,
  genre_id integer REFERENCES Genres (id) ON DELETE CASCADE NOT NULL,
  author integer REFERENCES playlist_user (id) ON DELETE CASCADE
);

